import type { Challenge, Order, TradingAccount, Invoice, Certificate, Notification, SupportTicket, Profile } from '@/types';

export const DEFAULT_CHALLENGES: Challenge[] = [
  // One Step
  {
    id: 'ch-one-5k',
    name: '5K One Step Challenge',
    type: 'one_step',
    account_size: 5000,
    price: 29,
    is_active: true,
    sort_order: 1,
    rules: {
      profit_target: 10,
      daily_drawdown: 4,
      max_drawdown: 8,
      min_trading_days: 3,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 80,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-one-10k',
    name: '10K One Step Challenge',
    type: 'one_step',
    account_size: 10000,
    price: 49,
    is_active: true,
    sort_order: 2,
    rules: {
      profit_target: 10,
      daily_drawdown: 4,
      max_drawdown: 8,
      min_trading_days: 3,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 80,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-one-25k',
    name: '25K One Step Challenge',
    type: 'one_step',
    account_size: 25000,
    price: 119,
    is_active: true,
    sort_order: 3,
    rules: {
      profit_target: 10,
      daily_drawdown: 4,
      max_drawdown: 8,
      min_trading_days: 3,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 85,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-one-50k',
    name: '50K One Step Challenge',
    type: 'one_step',
    account_size: 50000,
    price: 199,
    is_active: true,
    sort_order: 4,
    rules: {
      profit_target: 10,
      daily_drawdown: 4,
      max_drawdown: 8,
      min_trading_days: 3,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 85,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-one-100k',
    name: '100K One Step Challenge',
    type: 'one_step',
    account_size: 100000,
    price: 349,
    is_active: true,
    sort_order: 5,
    rules: {
      profit_target: 10,
      daily_drawdown: 4,
      max_drawdown: 8,
      min_trading_days: 3,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 90,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-one-200k',
    name: '200K One Step Challenge',
    type: 'one_step',
    account_size: 200000,
    price: 649,
    is_active: true,
    sort_order: 6,
    rules: {
      profit_target: 10,
      daily_drawdown: 4,
      max_drawdown: 8,
      min_trading_days: 3,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 90,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Two Step
  {
    id: 'ch-two-5k',
    name: '5K Two Step Evaluation',
    type: 'two_step',
    account_size: 5000,
    price: 24,
    is_active: true,
    sort_order: 7,
    rules: {
      profit_target: 8,
      daily_drawdown: 5,
      max_drawdown: 10,
      min_trading_days: 4,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 80,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-two-10k',
    name: '10K Two Step Evaluation',
    type: 'two_step',
    account_size: 10000,
    price: 45,
    is_active: true,
    sort_order: 8,
    rules: {
      profit_target: 8,
      daily_drawdown: 5,
      max_drawdown: 10,
      min_trading_days: 4,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 80,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-two-25k',
    name: '25K Two Step Evaluation',
    type: 'two_step',
    account_size: 25000,
    price: 99,
    is_active: true,
    sort_order: 9,
    rules: {
      profit_target: 8,
      daily_drawdown: 5,
      max_drawdown: 10,
      min_trading_days: 4,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 85,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-two-50k',
    name: '50K Two Step Evaluation',
    type: 'two_step',
    account_size: 50000,
    price: 179,
    is_active: true,
    sort_order: 10,
    rules: {
      profit_target: 8,
      daily_drawdown: 5,
      max_drawdown: 10,
      min_trading_days: 4,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 85,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-two-100k',
    name: '100K Two Step Evaluation',
    type: 'two_step',
    account_size: 100000,
    price: 299,
    is_active: true,
    sort_order: 11,
    rules: {
      profit_target: 8,
      daily_drawdown: 5,
      max_drawdown: 10,
      min_trading_days: 4,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 90,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-two-200k',
    name: '200K Two Step Evaluation',
    type: 'two_step',
    account_size: 200000,
    price: 549,
    is_active: true,
    sort_order: 12,
    rules: {
      profit_target: 8,
      daily_drawdown: 5,
      max_drawdown: 10,
      min_trading_days: 4,
      max_trading_days: 0,
      leverage: 100,
      profit_split: 90,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // Instant Funding
  {
    id: 'ch-inst-5k',
    name: '5K Instant Funding',
    type: 'instant_funding',
    account_size: 5000,
    price: 75,
    is_active: true,
    sort_order: 13,
    rules: {
      profit_target: 0,
      daily_drawdown: 3,
      max_drawdown: 6,
      min_trading_days: 7,
      max_trading_days: 0,
      leverage: 50,
      profit_split: 70,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-inst-10k',
    name: '10K Instant Funding',
    type: 'instant_funding',
    account_size: 10000,
    price: 129,
    is_active: true,
    sort_order: 14,
    rules: {
      profit_target: 0,
      daily_drawdown: 3,
      max_drawdown: 6,
      min_trading_days: 7,
      max_trading_days: 0,
      leverage: 50,
      profit_split: 70,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-inst-25k',
    name: '25K Instant Funding',
    type: 'instant_funding',
    account_size: 25000,
    price: 279,
    is_active: true,
    sort_order: 15,
    rules: {
      profit_target: 0,
      daily_drawdown: 3,
      max_drawdown: 6,
      min_trading_days: 7,
      max_trading_days: 0,
      leverage: 50,
      profit_split: 70,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-inst-50k',
    name: '50K Instant Funding',
    type: 'instant_funding',
    account_size: 50000,
    price: 479,
    is_active: true,
    sort_order: 16,
    rules: {
      profit_target: 0,
      daily_drawdown: 3,
      max_drawdown: 6,
      min_trading_days: 7,
      max_trading_days: 0,
      leverage: 50,
      profit_split: 70,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ch-inst-100k',
    name: '100K Instant Funding',
    type: 'instant_funding',
    account_size: 100000,
    price: 899,
    is_active: true,
    sort_order: 17,
    rules: {
      profit_target: 0,
      daily_drawdown: 3,
      max_drawdown: 6,
      min_trading_days: 7,
      max_trading_days: 0,
      leverage: 50,
      profit_split: 70,
      news_trading: true,
      weekend_holding: true,
      consistency: 0,
      scaling_plan: true,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEFAULT_ACCOUNTS: TradingAccount[] = [
  {
    id: 'acc-10001',
    order_id: 'ord-90124',
    user_id: 'demo-trader-id-12345',
    challenge_id: 'ch-one-100k',
    broker: 'FundedShift Direct ECN',
    account_number: '7829401',
    password: 'Password123!',
    investor_password: 'InvPass123!',
    server: 'FundedShift-Live01',
    platform: 'fundedshift_terminal',
    account_size: 100000,
    starting_balance: 100000,
    current_balance: 107450,
    profit: 7450,
    highest_balance: 108120,
    trading_days: 8,
    max_trading_days: 0,
    status: 'active',
    phase: 1,
    rules: DEFAULT_CHALLENGES[4].rules,
    assigned_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    challenge: DEFAULT_CHALLENGES[4],
  },
  {
    id: 'acc-10002',
    order_id: 'ord-90088',
    user_id: 'demo-trader-id-12345',
    challenge_id: 'ch-two-50k',
    broker: 'FundedShift Direct ECN',
    account_number: '5540192',
    password: 'Password123!',
    investor_password: 'InvPass123!',
    server: 'FundedShift-Funded',
    platform: 'fundedshift_terminal',
    account_size: 50000,
    starting_balance: 50000,
    current_balance: 54200,
    profit: 4200,
    highest_balance: 54200,
    trading_days: 22,
    max_trading_days: 0,
    status: 'funded',
    phase: 2,
    rules: DEFAULT_CHALLENGES[9].rules,
    assigned_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    challenge: DEFAULT_CHALLENGES[9],
  },
];

export const DEFAULT_ORDERS: Order[] = [
  {
    id: 'ord-90124',
    user_id: 'demo-trader-id-12345',
    challenge_id: 'ch-one-100k',
    account_size: 100000,
    platform: 'fundedshift_terminal',
    addons: [{ id: 'weekend_holding', name: 'Weekend Holding', price: 19, description: 'Hold positions over weekend' }],
    coupon_code: 'WELCOME10',
    discount_amount: 49.9,
    total_amount: 468.1,
    status: 'assigned',
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    challenge: DEFAULT_CHALLENGES[4],
  },
  {
    id: 'ord-90088',
    user_id: 'demo-trader-id-12345',
    challenge_id: 'ch-two-50k',
    account_size: 50000,
    platform: 'fundedshift_terminal',
    addons: [],
    coupon_code: null,
    discount_amount: 0,
    total_amount: 269,
    status: 'assigned',
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    challenge: DEFAULT_CHALLENGES[9],
  },
];

export const DEFAULT_INVOICES: Invoice[] = [
  {
    id: 'inv-1001',
    order_id: 'ord-90124',
    user_id: 'demo-trader-id-12345',
    invoice_number: 'INV-2026-0881',
    amount: 468.10,
    currency: 'USD',
    status: 'paid',
    pdf_url: null,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: 'inv-1002',
    order_id: 'ord-90088',
    user_id: 'demo-trader-id-12345',
    invoice_number: 'INV-2026-0712',
    amount: 269,
    currency: 'USD',
    status: 'paid',
    pdf_url: null,
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
];

export const DEFAULT_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-101',
    user_id: 'demo-trader-id-12345',
    account_id: 'acc-10002',
    title: 'OFFICIAL FUNDED TRADER',
    subtitle: 'Step 2 Completed & Account Funded',
    type: 'funded',
    recipient_name: 'Alex Rivera',
    account_size: 50000,
    account_number: '5540192',
    challenge_name: '50K Two Step Challenge',
    certificate_number: 'FS-CERT-2026-88402',
    issued_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'cert-102',
    user_id: 'demo-trader-id-12345',
    account_id: 'acc-10002',
    title: 'EVALUATION STEP 1 PASSED',
    subtitle: 'Phase 1 Target Reached & Verified',
    type: 'step1_passed',
    recipient_name: 'Alex Rivera',
    account_size: 50000,
    account_number: '5540192',
    challenge_name: '50K Two Step Challenge',
    certificate_number: 'FS-ST1-2026-90114',
    issued_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: 'cert-103',
    user_id: 'demo-trader-id-12345',
    account_id: 'acc-10002',
    title: 'PROFIT SPLIT PAYOUT',
    subtitle: 'Official Trader Reward Disbursement',
    type: 'payout',
    recipient_name: 'Alex Rivera',
    account_size: 50000,
    amount: 2450,
    account_number: '5540192',
    challenge_name: '50K Funded Account',
    certificate_number: 'FS-PAY-2026-10492',
    issued_at: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: 'cert-104',
    user_id: 'demo-trader-id-12345',
    account_id: 'acc-10002',
    title: 'FIRST PAYOUT MILESTONE',
    subtitle: '80% Profit Share Disbursement',
    type: 'payout',
    recipient_name: 'Alex Rivera',
    account_size: 50000,
    amount: 1250,
    account_number: '5540192',
    challenge_name: '50K Funded Account',
    certificate_number: 'FS-PAY-2026-00381',
    issued_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
];

export const DEFAULT_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    user_id: 'demo-trader-id-12345',
    title: 'Account Funded Successfully',
    body: 'Your $50,000 account has passed verification and is now active as a Funded Account.',
    type: 'success',
    is_read: false,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'demo-trader-id-12345',
    title: 'Profit Target Milestone Reached',
    body: 'You reached $7,450 profit on Account #7829401! Just $2,550 away from Phase 1 completion.',
    type: 'info',
    is_read: true,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const DEFAULT_TICKETS: SupportTicket[] = [
  {
    id: 'tick-501',
    user_id: 'demo-trader-id-12345',
    subject: 'Request for Leverage Upgrade on MT5',
    category: 'General',
    priority: 'normal',
    status: 'closed',
    messages: [
      {
        sender: 'user',
        message: 'Hello, I purchased the higher leverage addon on my 100K challenge. Please confirm it is active.',
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
];
